/* Pip's English: reusable world/progression shell. No vocabulary or game rules here. */
(() => {
  'use strict';
  const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem('pip_english_'+key))??fallback;}catch{return fallback;}};
  const save=(key,value)=>{try{localStorage.setItem('pip_english_'+key,JSON.stringify(value));}catch{}};
  const regions={
    2:{name:'Sky Islands',story:'The islands are rising! Light the sky beacon and help the villagers find a safe path.',routes:[['sky','Sunbeam Village','A gentle beginning'],['sky-alt','Cloud Harbour','Double stars · extra adverbs']]},
    3:{name:'Floating Forest',story:'The forest homes are drifting apart. Follow the fireflies and light the forest beacon.',routes:[['forest','Waterfall Woods','Double stars · extra adverbs'],['forest-alt','Moonlit Canopy','Phase 2 words · half stars']]},
    4:{name:'Crystal Peaks',story:'The crystal beacon has gone quiet. Guide the mountain villagers across the frozen sky.',routes:[['crystal','Crystal Caverns','Double stars · extra adverbs'],['crystal-alt','Aurora Glacier','Phase 3 words · half stars']]},
    5:{name:'Ember Volcano',story:'The last beacon waits above the lava. Bring the light home and settle the floating islands.',routes:[['volcano','Ember Ascent','Double stars · extra adverbs'],['volcano-alt','Lava Lanterns','Phase 4 words · half stars']]}
  };
  let mode=read('mode','classic');if(!['classic','learning'].includes(mode))mode='classic';
  let records=read('records',{}),route=0,api,resolveRoute=null,mapPhase=2,returnFocus=null,hubActive=false;
  const $=id=>document.getElementById(id);
  const settings=phase=>({mode,route,wordPhase:mode==='classic'&&route===1&&phase>2?phase-1:phase,extraAdverbs:mode==='classic'&&((route===0&&phase>2)||(route===1&&phase===2)),multiplier:mode==='learning'?1:route===1&&phase>2?.5:((route===0&&phase>2)||(route===1&&phase===2))?2:1});
  const unlock=()=>Math.min(5,Math.max(2,read('unlocked_'+mode,mode==='classic'?Number(JSON.parse(localStorage.getItem('wordwind_unlockedPhase')||'2')):2)));
  function key(phase,r=route){return `${mode}:${phase}:${r}`;}
  function record(phase,score,complete=false){const k=key(phase);records[k]={best:Math.max(records[k]?.best||0,score),complete:!!(complete||records[k]?.complete)};save('records',records);if(complete)save('unlocked_'+mode,Math.max(unlock(),Math.min(5,phase+1)));}
  function element(tag,attrs={},text=''){const e=document.createElement(tag);for(const [k,v]of Object.entries(attrs))e.setAttribute(k,v);e.textContent=text;return e;}
  function open(panel){returnFocus=document.activeElement;panel.hidden=false;api.stopVoice();document.querySelectorAll('#game > *').forEach(e=>{if(e!==panel)e.inert=true;});panel.querySelector('button')?.focus({preventScroll:true});}
  function close(panel){panel.hidden=true;document.querySelectorAll('#game > *').forEach(e=>e.inert=false);returnFocus?.focus({preventScroll:true});api.ground();}
  function showMap(choosing=false,phase=api.state.selectedPhase){mapPhase=phase;$('mapTitle').textContent=choosing?'Choose the next path':'The floating islands';$('mapClose').hidden=choosing;$('mapHint').textContent=choosing?'Beacon restored! Choose one route to keep travelling.':'Tap a stop to inspect its routes and your best score. Scroll to explore.';renderMap(choosing);open($('journeyMap'));}
  function renderMap(choosing=false){
    const board=$('mapBoard');board.replaceChildren();const art=element('img',{src:'assets/journey/map.webp',alt:'An ascending journey from sky villages through forests and crystal mountains to a volcano.'});board.append(art);
    for(const phase of [5,4,3,2]){const locked=phase>unlock();const b=element('button',{class:'map-stop'+(phase===mapPhase?' selected':''),'aria-pressed':String(phase===mapPhase),'data-phase':phase,style:`top:${({2:84,3:58,4:36,5:18})[phase]}%;left:50%`},`${locked?'Locked · ':''}${phase} · ${regions[phase].name}`);b.onclick=()=>{mapPhase=phase;renderMap(choosing);};board.append(b);}
    const detail=$('mapDetail');detail.replaceChildren();detail.append(element('p',{class:'eyebrow'},`Phase ${mapPhase} · ${mode==='learning'?'Learning':'Classic'}`),element('h2',{},regions[mapPhase].name),element('p',{},regions[mapPhase].story));
    if(mode==='classic')detail.append(element('p',{},'Star modifiers apply to leaps. Every restored beacon also earns 5 stars.'));
    regions[mapPhase].routes.forEach(([asset,name,modifier],i)=>{const rec=records[key(mapPhase,i)];const card=element('article',{class:'route-card'});card.append(element('img',{src:`assets/journey/${asset}.webp`,alt:'',loading:'lazy'}),element('h3',{},name),element('p',{},mode==='learning'?'Same learning journey · no modifiers':modifier),element('p',{class:'route-record'},rec?`Best: ${rec.best} correct leaps${rec.complete?' · Beacon lit':''}`:'Not travelled yet'));
      const allowed=mapPhase<=unlock()&&(!choosing||mapPhase===api.state.phase+1);const btn=element('button',{class:'primary-button'},mapPhase>unlock()?'Locked — light the previous beacon':choosing?'Take this path':api.state.running?'View only during a run':'Travel here');btn.disabled=!allowed||(!choosing&&api.state.running);btn.onclick=()=>{route=i;close($('journeyMap'));if(resolveRoute){const done=resolveRoute;resolveRoute=null;done(i);}else{api.state.selectedPhase=mapPhase;hideHub();api.beginStory();}};card.append(btn);detail.append(card);});
    if(choosing)detail.prepend(element('p',{class:'route-notice'},'Your next destination is Phase '+(api.state.phase+1)+'. You can inspect other stops, but cannot skip a beacon.'));
  }
  function chooseNext(phase){record(phase,api.state.score-api.state.stageStart,true);return new Promise(resolve=>{resolveRoute=resolve;showMap(true,phase+1);});}
  function apply(phase){const info=regions[phase],r=info.routes[route];$('skyScene').style.backgroundImage=`url("assets/journey/${r[0]}.webp")`;$('game').dataset.mode=mode;$('routeBadge').textContent=`${r[1]} · ${mode==='learning'?'Learning':r[2]}`;}
  function showHub(){hubActive=true;$('villageHub').hidden=false;$('game').classList.add('in-village');api.state.running=false;api.state.busy=false;api.stopVoice();api.hideMenus();document.querySelectorAll('#game > *').forEach(e=>e.inert=false);setMode(mode);$('hubStars').textContent=api.state.coins;placePip();}
  function hideHub(){hubActive=false;$('villageHub').hidden=true;$('game').classList.remove('in-village');}
  function setMode(next){mode=next;save('mode',mode);api.state.unlockedPhase=unlock();save('unlocked_'+mode,api.state.unlockedPhase);api.state.selectedPhase=Math.min(api.state.selectedPhase,unlock());$('game').dataset.mode=mode;document.querySelectorAll('[data-play-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.playMode===mode)));$('hubModeHelp').textContent=mode==='classic'?'Branching paths, star bonuses and a useful trail pack.':'A calm word journey. Free explanations, no powerups or route modifiers.';api.refresh();}
  const pos={x:50,y:76},keys=new Set();let last=0,target=null,arrived=null;
  const places=[{id:'hubBook',x:25,y:57,action:()=>{hideHub();api.openBook();}},{id:'hubMap',x:43,y:50,action:()=>showMap()},{id:'hubShop',x:66,y:56,action:()=>{hideHub();api.openShop();}},{id:'hubPlay',x:89,y:70,action:()=>showMap()}];
  function placePip(){const p=$('hubPip');p.style.left=pos.x+'%';p.style.top=pos.y+'%';}
  function frame(time){const dt=Math.min((time-last)/1000,.04);last=time;const active=hubActive&&$('journeyMap').hidden&&!$('villageHub').inert;let dx=0,dy=0;if(active){dx=(keys.has('ArrowRight')?1:0)-(keys.has('ArrowLeft')?1:0);dy=(keys.has('ArrowDown')?1:0)-(keys.has('ArrowUp')?1:0);if(dx||dy){target=null;arrived=null;}else if(target){dx=target.x-pos.x;dy=target.y-pos.y;if(Math.hypot(dx,dy)<1.2){const action=target.action;target=null;arrived=null;action?.();dx=dy=0;}}if(dx||dy){const length=Math.hypot(dx,dy);pos.x=Math.max(15,Math.min(91,pos.x+dx/length*dt*24));pos.y=Math.max(48,Math.min(87,pos.y+dy/length*dt*30));$('hubPip').classList.toggle('face-left',dx<0);placePip();}const nearest=places.find(p=>Math.hypot(p.x-pos.x,p.y-pos.y)<7);arrived=nearest||null;$('hubInteract').disabled=!nearest;$('hubInteract').textContent=nearest?'Enter '+$(nearest.id).textContent:'Walk to a doorway';}$('hubPip').classList.toggle('walking',!!(dx||dy));requestAnimationFrame(frame);}
  function attach(gameApi){
    api=gameApi;const game=$('game');
    const hub=element('section',{id:'villageHub','aria-label':"Pip's English village"});hub.innerHTML=`<header class="village-header"><div><p class="eyebrow">Welcome to</p><h1>Pip’s English</h1></div><div class="village-wallet">✦ <span id="hubStars">0</span><small>Stars saved on this device</small></div></header><div class="mode-switch" aria-label="Choose game mode"><button data-play-mode="classic" type="button">Classic<span>Adventure & surprises</span></button><button data-play-mode="learning" type="button">Learning<span>Calm, guided practice</span></button></div><p id="hubModeHelp"></p><div class="village-stage" id="villageStage"><button class="village-door" id="hubBook" style="left:25%;top:52%">Word book</button><button class="village-door" id="hubMap" style="left:43%;top:39%">Map</button><button class="village-door" id="hubShop" style="left:66%;top:49%">Supply stop</button><button class="village-door play-door" id="hubPlay" style="left:89%;top:65%">Go play</button><div id="hubPip" aria-hidden="true"><div class="pip-atlas-frame"></div></div></div><footer class="village-footer"><p>Arrow keys to walk · Enter to visit<br>On iPad, tap a doorway to walk there.</p><button id="hubInteract" class="secondary-button" disabled>Walk to a doorway</button><button id="hubSound" class="secondary-button">Sound</button></footer>`;game.append(hub);
    const map=element('section',{id:'journeyMap',class:'adventure-panel',role:'dialog','aria-modal':'true','aria-labelledby':'mapTitle',hidden:''});map.innerHTML='<header class="adventure-header"><div><p class="eyebrow">Pip’s rescue trail</p><h1 id="mapTitle">The floating islands</h1><p id="mapHint"></p></div><button id="mapClose" class="secondary-button">Close map</button></header><div class="map-layout"><div id="mapBoard" class="map-board"></div><div id="mapDetail" class="map-detail"></div></div>';game.append(map);
    const nav=element('nav',{class:'adventure-nav','aria-label':'Journey navigation'});nav.innerHTML='<button id="runMap">Map</button><button id="runHome">Village</button><span id="routeBadge"></span>';game.append(nav);
    $('mapClose').onclick=()=>close(map);$('runMap').onclick=()=>{if(!api.state.busy)showMap();};$('runHome').onclick=()=>{if(api.state.busy)return;if(!api.state.running||confirm('Return to the village? Your stars and best scores are saved; this run will end.')){record(api.state.phase,api.state.score-api.state.stageStart);showHub();}};
    $('hubSound').onclick=()=>api.toggleSound();document.querySelectorAll('[data-play-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.playMode));places.forEach(p=>$(p.id).onclick=()=>{target=p;});$('hubInteract').onclick=()=>arrived?.action();
    $('villageStage').tabIndex=0;
    $('villageStage').addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;const r=e.currentTarget.getBoundingClientRect();target={x:Math.max(15,Math.min(91,(e.clientX-r.left)/r.width*100)),y:Math.max(48,Math.min(87,(e.clientY-r.top)/r.height*100))};});
    document.addEventListener('keydown',e=>{if(hubActive&&map.hidden&&!hub.inert&&!e.target.closest('input,select')){if(e.key.startsWith('Arrow')){e.preventDefault();keys.add(e.key);$('villageStage').focus({preventScroll:true});}if(e.key==='Enter'&&(e.target===document.body||e.target===$('villageStage'))){e.preventDefault();arrived?.action();}}if(e.key==='Escape'&&!map.hidden&&!resolveRoute)close(map);
      const panel=!map.hidden?map:null;if(panel&&e.key==='Tab'){const list=[...panel.querySelectorAll('button:not(:disabled)')].filter(b=>!b.hidden);if(e.shiftKey&&document.activeElement===list[0]){e.preventDefault();list.at(-1).focus();}else if(!e.shiftKey&&document.activeElement===list.at(-1)){e.preventDefault();list[0].focus();}}});document.addEventListener('keyup',e=>keys.delete(e.key));window.addEventListener('blur',()=>keys.clear());requestAnimationFrame(frame);
    // Counter items open the existing, tested purchase controls; no purchase on entry.
    const shop=$('shopOverlay'),modal=shop.querySelector('.shop-modal');const counter=element('div',{class:'supply-room','aria-label':'Inspect items on the counter'});counter.innerHTML='<p class="counter-caption">Tap an item to inspect it</p><div class="counter-items"><button data-inspect="shield">◈<span>Cloud shield</span></button><button data-inspect="heart">♥<span>Brave heart</span></button><button data-inspect="boots">♜<span>Star boots</span></button><button data-inspect="cosmetics">✦<span>Pip’s colours</span></button></div><div class="shop-visitor pip-atlas-frame" aria-hidden="true"></div>';modal.querySelector('.next-reward').before(counter);modal.querySelector('.shop-grid').classList.add('stock-details');counter.querySelectorAll('[data-inspect]').forEach(b=>b.onclick=()=>{const item=b.dataset.inspect;modal.dataset.inspect=item;const area=item==='cosmetics'?$('cosmeticGrid'):modal.querySelector(`[data-item="${item}"]`).closest('article');area.scrollIntoView({behavior:'smooth',block:'nearest'});area.querySelector('button')?.focus({preventScroll:true});});modal.dataset.inspect='cosmetics';for(const item of ['shield','heart','boots']){const button=counter.querySelector('[data-inspect="'+item+'"]');button.firstChild.remove();const svg=modal.querySelector('[data-item="'+item+'"]').closest('article').querySelector('svg').cloneNode(true);button.prepend(svg);}$('backToTrailButton').textContent='Leave the supply stop';
    let shopWasOpen=false;
    new MutationObserver(()=>{const isOpen=shop.classList.contains('open'),justClosed=shopWasOpen&&!isOpen;shopWasOpen=isOpen;if(justClosed&&!api.state.running&&!$('dictionaryOverlay').classList.contains('open')&&$('journeyMap').hidden&&!$('storyOverlay').classList.contains('open'))showHub();}).observe(shop,{attributes:true,attributeFilter:['class']});
  }
  window.PipAdventure={attach,settings,apply,record,chooseNext,showHub,hideHub,get mode(){return mode;},get regions(){return regions;}};
})();
