/* The shop and mirror share a single catalogue; navigation stays in world.js. */
window.PipOutfitters=(()=>{
  const $=id=>document.getElementById(id);let wardrobe,options,category='head',filter='all',magic='glow',revision=0,ready=false;
  const button=(label,fn,attrs={})=>{const b=document.createElement('button');b.type='button';b.textContent=label;Object.entries(attrs).forEach(([k,v])=>b.setAttribute(k,v));b.onclick=fn;return b;};
  function markup(){return `<div class="outfitters-panel parchment"><header class="outfitters-header"><div><small>PIP’S OUTFITTERS</small><h1 id="wardrobeTitle">Make it yours</h1><p>Try anything. Keep your favourites with saved stars.</p></div><div class="outfitters-wallet">✦ <strong id="wardrobeBalance"></strong><span>saved stars</span></div><button id="wardrobeClose" class="close-mark" aria-label="Close wardrobe">×</button></header><div class="outfitters-body"><aside class="dressing-side"><div class="dressing-mirror" id="dressingMirror"><div class="mirror-character"><div id="wardrobePreview" class="pip-atlas-frame"></div></div></div><div class="preview-actions"><button id="previewStand">Stand</button><button id="previewWalk">Walk</button><button id="previewJump">Jump</button></div><p class="preview-note">A free try-on. Only “Buy & wear” spends stars.</p><button id="wardrobeReset" class="quiet-button">Reset look</button><div class="saved-looks"><h2>My saved looks</h2><div id="wardrobePresets"></div></div></aside><section class="wardrobe-catalogue"><div class="catalogue-filter"><button id="wardrobeBrowse" aria-pressed="true">Browse</button><button id="wardrobeOwned" aria-pressed="false">My wardrobe</button></div><nav id="wardrobeCategories" class="wardrobe-categories" role="tablist" aria-label="Clothing categories"></nav><div id="magicCategories" class="magic-categories" hidden><button id="magicGlows" aria-pressed="true">Glows</button><button id="magicChimes" aria-pressed="false">Chimes</button></div><div id="wardrobeItems" class="wardrobe-items" role="tabpanel" aria-label="Items"></div><footer class="wardrobe-selection"><div><small id="wardrobeFamily"></small><h2 id="wardrobeItemName"></h2><p id="wardrobeItemDetail"></p></div><button id="wardrobeBuy" class="wood-button"></button><button id="wardrobeSound" class="quiet-button" hidden>Hear chime</button><p id="wardrobeStatus" role="status" aria-live="polite"></p></footer></section></div></div>`;}
  function selected(){return wardrobe.items.find(i=>i.id===wardrobe.selected);}
  function action(){const i=selected();if(!i)return;const b=$('wardrobeBuy');const wearing=JSON.stringify(wardrobe.look)===JSON.stringify(wardrobe.equipped);const short=Math.max(0,i.cost-wardrobe.balance);b.textContent=wardrobe.busy?'Saving…':!ready?'Loading look…':wearing?'Wearing':i.owned?'Wear':short?`Need ${short} more stars`:`Buy & wear · ${i.cost} stars`;b.disabled=wardrobe.busy||!ready||wearing||(!i.owned&&short>0);}
  function render(status=''){
    if(!wardrobe||!$('wardrobeItems'))return;const turn=++revision,focus=document.activeElement?.dataset.item;
    const slot=category==='magic'?magic:category,items=wardrobe.items.filter(i=>i.slot===slot&&(filter==='all'||i.owned));
    $('wardrobeBalance').textContent=wardrobe.balance;$('wardrobeBrowse').setAttribute('aria-pressed',filter==='all');$('wardrobeOwned').setAttribute('aria-pressed',filter==='owned');
    const cats=$('wardrobeCategories');cats.replaceChildren();for(const [id,label] of PipCosmetics.categories){const b=button(label,()=>{category=id;render();},{role:'tab','aria-selected':String(id===category),'aria-controls':'wardrobeItems',tabindex:id===category?'0':'-1'});b.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const list=PipCosmetics.categories,index=list.findIndex(c=>c[0]===category);category=list[e.key==='Home'?0:e.key==='End'?list.length-1:(index+(e.key==='ArrowRight'?1:list.length-1))%list.length][0];render();cats.querySelector('[aria-selected="true"]').focus();};cats.append(b);}
    $('magicCategories').hidden=category!=='magic';$('magicGlows').setAttribute('aria-pressed',magic==='glow');$('magicChimes').setAttribute('aria-pressed',magic==='chime');
    const grid=$('wardrobeItems');grid.replaceChildren();for(const item of items){const card=button('',()=>{wardrobe.select(item.id);render();},{class:'cosmetic-card','data-item':item.id,'aria-pressed':String(item.id===wardrobe.selected),'aria-label':`${item.name}, ${item.equipped?'wearing':item.owned?'owned':item.cost+' saved stars'}`});const img=new Image();img.src=item.icon;img.alt='';img.loading='lazy';const name=document.createElement('strong');name.textContent=item.name;const price=document.createElement('span');price.textContent=item.equipped?'✓ Wearing':item.owned?'Owned':`✦ ${item.cost}`;card.append(img,name,price);if(item.swatch)card.style.setProperty('--item-colour',item.swatch);grid.append(card);}
    if(!items.length){const p=document.createElement('p');p.className='wardrobe-empty';p.textContent='Your collection starts here. Browse to find a favourite.';grid.append(p);}
    if(focus)grid.querySelector(`[data-item="${focus}"]`)?.focus({preventScroll:true});
    const item=selected();$('wardrobeFamily').textContent=item?.family||'';$('wardrobeItemName').textContent=item?.name||'Choose a treasure';$('wardrobeItemDetail').textContent=item?.slot==='held'?'Adventure style. No power-ups or damage bonus.':item?.slot==='fur'?'A new fur colour; Pip’s markings stay his own.':item?.legacy?'An original costume. Choose a clothing piece to start a new mix.':'Mix colours and treasures to make your own Pip.';
    $('wardrobeSound').hidden=item?.id!=='chime';$('wardrobeStatus').textContent=wardrobe.error||status;ready=false;action();
    PipAppearance.render(wardrobe.look,[$('wardrobePreview')]).then(()=>{if(turn!==revision)return;ready=true;action();}).catch(()=>{if(turn!==revision)return;$('wardrobeStatus').textContent='This preview could not load. No stars were spent.';ready=false;action();});
    const presets=$('wardrobePresets');presets.replaceChildren();wardrobe.presets.forEach((look,index)=>{const box=document.createElement('div');box.className='saved-look';const wear=button(look?'Wear look '+(index+1):'Look '+(index+1),async()=>{await wardrobe.wearPreset(index);render();});wear.disabled=!look;const save=button('Save',async()=>{const ok=await wardrobe.savePreset(index);render(ok?'Look saved.':'');},{'aria-label':'Save current look '+(index+1)});if(look){const img=new Image();img.alt='';PipAppearance.compose(look).then(r=>{if(img.isConnected)img.src=r.thumb;}).catch(()=>{});wear.prepend(img);}box.append(wear,save);presets.append(box);});
  }
  function mount(model,config){wardrobe=model;options=config;$('wardrobeClose').onclick=options.close;$('wardrobeBrowse').onclick=()=>{filter='all';render();};$('wardrobeOwned').onclick=()=>{filter='owned';render();};$('magicGlows').onclick=()=>{magic='glow';render();};$('magicChimes').onclick=()=>{magic='chime';render();};$('wardrobeBuy').onclick=async()=>{const wasOwned=selected()?.owned,ok=await wardrobe.buyOrEquip();render(ok?(wasOwned?'Pip is wearing your choice.':'It’s yours! Pip is wearing it.'):wardrobe.error);};$('wardrobeReset').onclick=async()=>{await wardrobe.reset();render('Original look restored.');};$('wardrobeSound').onclick=options.previewSound;for(const [id,mode] of [['previewStand',''],['previewWalk','preview-walk'],['previewJump','preview-jump']])$(id).onclick=()=>{$('dressingMirror').classList.remove('preview-walk','preview-jump');if(mode)$('dressingMirror').classList.add(mode);};window.addEventListener('wardrobechange',()=>{if(!$('wardrobePanel').hidden)render();});}
  return {markup,mount,render,setCategory(id){category=id;filter='all';}};
})();
