/* Shared-device practice evidence only. Never reads or resets either wallet. */
window.PipPractice={create({entries,storage,day=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');}}){
 const key='pip_english_practice_v1',words=new Set(entries.map(e=>e.word)),kinds=['noun','verb','adjective','adverb'];let data={version:1,records:{},regions:{},recent:[],recentAttempts:[],maxDay:''},attempts=new Set();
 const count=n=>Math.max(0,Math.min(1000000,Math.floor(Number(n)||0)));
 try{const old=JSON.parse(storage.getItem(key));if(old?.version===1){for(const [id,r] of Object.entries(old.records||{})){const [word,kind]=id.split(':');if(words.has(word)&&kinds.includes(kind))data.records[id]={seen:count(r.seen),attempted:count(r.attempted),independent:count(r.independent),assisted:count(r.assisted),xp:Math.min(12,count(r.xp)),days:Math.min(6,count(r.days)),lastDay:/^\d{4}-\d{2}-\d{2}$/.test(r.lastDay)?r.lastDay:''};}for(const phase of [2,3,4,5]){data.regions[phase]={};for(const [word,n] of Object.entries(old.regions?.[phase]||{}))if(words.has(word))data.regions[phase][word]=count(n);}data.maxDay=/^\d{4}-\d{2}-\d{2}$/.test(old.maxDay)?old.maxDay:'';data.recent=Array.isArray(old.recent)?old.recent.filter(s=>typeof s==='string').slice(-32):[];data.recentAttempts=Array.isArray(old.recentAttempts)?old.recentAttempts.filter(s=>typeof s==='string').slice(-64):[];attempts=new Set(data.recentAttempts);}}catch{}
 const save=()=>{try{storage.setItem(key,JSON.stringify(data));}catch{}};
 const record=(word,kind)=>{if(!words.has(word)||!kinds.includes(kind))return null;return data.records[word+':'+kind]??= {seen:0,attempted:0,independent:0,assisted:0,xp:0,days:0,lastDay:''};};
 function present(id,phase,options,target){if(data.recent.includes(id))return;data.recent=[...data.recent,id].slice(-32);const region=data.regions[phase]??={};for(const word of new Set(options.map(o=>o.word))){const r=record(word,target);if(!r)continue;r.seen=count(r.seen+1);region[word]=count((region[word]||0)+1);}save();}
 function attempt(id,word,kind,{correct,assisted=false,firstTry=true}){const token=id+':'+word+':'+kind;if(attempts.has(token))return false;const r=record(word,kind);if(!r)return false;attempts.add(token);data.recentAttempts=[...attempts].slice(-64);attempts=new Set(data.recentAttempts);r.attempted=count(r.attempted+1);const today=day();if(correct){if(assisted||!firstTry)r.assisted=count(r.assisted+1);else{r.independent=count(r.independent+1);if(today>=data.maxDay&&today>r.lastDay){r.xp=Math.min(12,r.xp+2);r.days=Math.min(6,r.days+1);r.lastDay=today;}}}if(today>data.maxDay)data.maxDay=today;save();return true;}
 function get(word,kind){const r=data.records[word+':'+kind]||{seen:0,attempted:0,independent:0,assisted:0,xp:0,days:0};return {...r,stars:[[2,1],[6,3],[12,6]].filter(([xp,days])=>r.xp>=xp&&r.days>=days).length};}
 function top(phase){return Object.entries(data.regions[phase]||{}).filter(([,n])=>n>0).sort((a,b)=>b[1]-a[1]||(a[0]<b[0]?-1:a[0]>b[0]?1:0)).slice(0,5).map(([word,seen])=>({word,seen}));}
 return {present,attempt,get,top,export:()=>JSON.stringify(data,null,2),reset(){data={version:1,records:{},regions:{},recent:[],maxDay:''};attempts.clear();save();}};
}};
