/* Scene navigation and saved journey records; game rules stay in game.js. */
(() => {
  'use strict';
  const $=id=>document.getElementById(id);
  const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem('pip_english_'+key))??fallback;}catch{return fallback;}};
  const save=(key,value)=>{try{localStorage.setItem('pip_english_'+key,JSON.stringify(value));}catch{}};
  const regions={
    2:{name:'Sky Islands',story:'Light the sky beacon and help the villagers find a safe path.',routes:[['sky','Sunbeam Village','A gentle beginning'],['sky-alt','Cloud Harbour','Double stars · extra adverbs']]},
    3:{name:'Floating Forest',story:'The forest homes are drifting apart. Follow the fireflies to their beacon.',routes:[['forest','Waterfall Woods','Double stars · extra adverbs'],['forest-alt','Moonlit Canopy','Phase 2 words · half stars']]},
    4:{name:'Crystal Peaks',story:'Guide the mountain villagers across the frozen sky.',routes:[['crystal','Crystal Caverns','Double stars · extra adverbs'],['crystal-alt','Aurora Glacier','Phase 3 words · half stars']]},
    5:{name:'Ember Volcano',story:'Bring the last beacon’s light home and settle the floating islands.',routes:[['volcano','Ember Ascent','Double stars · extra adverbs'],['volcano-alt','Lava Lanterns','Phase 4 words · half stars']]}
  };
  let mode='learning',route=0,api,scene='village',mapPhase=2,resolveRoute,resolveStop,focusBefore,modal;
  const records=read('records',{}),positions={hubPip:{x:50,y:80},shopPip:{x:50,y:85}};
  let walk=null,last=0,transition=0;
  const settings=phase=>({mode,route,wordPhase:mode==='classic'&&route===1&&phase>2?phase-1:phase,extraAdverbs:mode==='classic'&&((route===0&&phase>2)||(route===1&&phase===2)),multiplier:mode==='learning'?1:route===1&&phase>2?.5:((route===0&&phase>2)||(route===1&&phase===2))?2:1});
  function unlock(){let legacy=2;if(mode==='classic'){try{legacy=JSON.parse(localStorage.getItem('wordwind_unlockedPhase')||'2');}catch{}}return Math.max(2,Math.min(5,Number(read('unlocked_'+mode,legacy))||2));}
  const recordKey=(p,r=route)=>`${mode}:${p}:${r}`;
  function record(phase,score,complete=false){const key=recordKey(phase),old=records[key];records[key]={best:Math.max(old?.best||0,score),complete:!!(complete||old?.complete)};save('records',records);if(complete)save('unlocked_'+mode,Math.max(unlock(),Math.min(5,phase+1)));}
  function el(tag,attrs={},text=''){const e=document.createElement(tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));e.textContent=text;return e;}
  function panel(id,title,html){const p=el('section',{id,class:'scene-dialog',role:'dialog','aria-modal':'true','aria-label':title,hidden:''});p.innerHTML=html;$('game').append(p);return p;}
  function inert(){[...$('game').children].forEach(e=>{e.inert=modal?e!==modal:scene==='village'?e!==$('villageHub'):scene==='shop'?e!==$('supplyScene'):false;});}
  function sceneMusic(){PipSoundtrack.scene(modal===$('journeyMap')?'map':scene==='game'?(mode==='classic'&&api.state.phase===5&&api.state.bossMode?'finale':({2:'sky',3:'forest',4:'crystal',5:'volcano'}[api.state.phase])):scene);}
  function open(p){focusBefore=document.activeElement;modal=p;p.hidden=false;api.stopVoice();inert();p.querySelector('button')?.focus();sceneMusic();}
  function close(p){if(p.id==='wardrobePanel')api.wardrobe.close();p.hidden=true;modal=null;inert();focusBefore?.focus({preventScroll:true});api.ground();sceneMusic();}
  function setScene(next){scene=next;walk=null;transition++;for(const id of ['hubPip','shopPip']){$(id).classList.remove('walking','entering','face-left');$(id).dataset.navigation='standing';}if(next==='shop'){positions.shopPip=PipNavigation.point('shop','spawn');place('shopPip');}$('villageHub').hidden=next!=='village';$('supplyScene').hidden=next!=='shop';$('game').classList.toggle('in-village',next!=='game');inert();sceneMusic();}
  function showHub(destination='spawn'){api.wardrobe.close();api.cancelRun();api.state.running=false;api.supplies.leave();resolveStop?.();resolveStop=null;resolveRoute?.(null);resolveRoute=null;api.state.busy=false;api.stopVoice();api.hideMenus();document.querySelectorAll('.scene-dialog').forEach(e=>e.hidden=true);modal=null;setScene('village');positions.hubPip=PipNavigation.point('village',destination);place('hubPip');setMode(mode);$('hubStars').textContent=api.state.coins;}
  function hideHub(){setScene('game');}
  function setMode(value){mode=value;api.state.unlockedPhase=unlock();api.state.selectedPhase=2;$('game').dataset.mode=mode;document.querySelectorAll('[data-play-mode]').forEach(e=>e.setAttribute('aria-pressed',String(e.dataset.playMode===mode)));$('playModeHelp').textContent=mode==='learning'?'Free explanations and gentle retries. No powerups or surprise rules.':'Choose branching routes with star bonuses and surprises. Three word-type reveals per run.';api.refresh();}
  function apply(phase){const r=regions[phase].routes[route];$('skyScene').style.backgroundImage=`url("assets/journey/${r[0]}.webp")`;$('routeBadge').textContent=r[1];sceneMusic();}
  function showPlay(){setMode('learning');$('playAdverbs').checked=api.state.includeAdverbs;open($('playSetup'));}
  function resetRun(){route=0;api.state.selectedPhase=2;}
  function showMap(){mapPhase=api.state.running?api.state.phase:2;renderMap();open($('journeyMap'));}
  function renderMap(){
    const board=$('mapBoard'),detail=$('mapDetail');board.replaceChildren(el('img',{src:'assets/journey/map.webp',alt:'The floating-island trail.'}));
    [5,4,3,2].forEach(phase=>{const locked=phase>unlock(),top={2:84,3:58,4:36,5:18}[phase];if(locked)board.append(el('div',{class:'map-fog',style:`top:${top-14}%;height:26%`,'aria-hidden':'true'}));const b=el('button',{class:'map-stop'+(phase===mapPhase?' selected':''),'data-phase':phase,style:`top:${top}%;left:50%`},locked?'🔒 ????':regions[phase].name);b.onclick=()=>{mapPhase=phase;renderMap();};board.append(b);});
    detail.replaceChildren();if(mapPhase>unlock()){detail.append(el('h2',{},'🔒 ????'),el('p',{},'Restore the previous beacon to discover this place.'));return;}
    detail.append(el('p',{class:'eyebrow'},mode==='learning'?'Learning journey':'Classic journey'),el('h2',{},regions[mapPhase].name),el('p',{},regions[mapPhase].story));
    const familiar=api.practice.top(mapPhase),drawer=el('details',{class:'familiar-drawer'}),summary=el('summary',{},'Most seen here'),drawerBody=el('div',{class:'familiar-words'});drawer.append(summary,el('p',{},'Shared-device sightings, not mastery. Ties use alphabetical order.'),drawerBody);detail.append(drawer);
    if(!familiar.length)drawerBody.append(el('p',{},'No familiar words yet. Words appear after practice in this region.'));
    familiar.forEach(({word,seen})=>{const b=el('button',{class:'familiar-word'},word+' · '+seen+' times seen');b.onclick=()=>{close($('journeyMap'));hideHub();api.openPracticeWord(word,mapPhase);};drawerBody.append(b);});
    regions[mapPhase].routes.forEach(([asset,name],r)=>{const rec=records[recordKey(mapPhase,r)],card=el('article',{class:'route-card'});card.append(el('img',{src:`assets/journey/${asset}.webp`,alt:'',loading:'lazy'}),el('h3',{},name),el('p',{},rec?`Best: ${rec.best} correct leaps${rec.complete?' · Beacon lit':''}`:'Not travelled yet'));detail.append(card);});detail.append(el('p',{},'Start at Go play in the village. Choose your next path as you travel.'));
  }
  function chooseNext(phase){record(phase,api.state.score-api.state.stageStart,true);$('nextRegion').textContent=regions[phase+1].name;const cards=$('routeCards');cards.replaceChildren();return new Promise(resolve=>{resolveRoute=resolve;regions[phase+1].routes.forEach(([asset,name,rule],i)=>{const b=el('button',{class:'route-card'});b.append(el('img',{src:`assets/journey/${asset}.webp`,alt:''}),el('h3',{},name),el('p',{},mode==='learning'?'A new path · the same gentle learning':rule));b.onclick=()=>{if(!resolveRoute)return;route=i;close($('routeChoice'));resolveRoute=null;resolve(i);};cards.append(b);});open($('routeChoice'));});}
  function checkpointStop(){if(mode!=='classic')return Promise.resolve();return new Promise(resolve=>{resolveStop=resolve;$('stopStars').textContent=api.supplies.stars;open($('checkpointStop'));$('visitStop').onclick=()=>{if(!resolveStop)return;close($('checkpointStop'));api.supplies.enter();openShop();};$('skipStop').onclick=()=>{if(!resolveStop)return;close($('checkpointStop'));resolveStop=null;resolve();};});}
  function place(id){const p=positions[id];$(id).style.left=p.x+'%';$(id).style.top=p.y+'%';}
  function closeItem(){$('itemCard').hidden=true;$('supplyScene').classList.remove('inspecting');}
  function walkTo(id,destination,action){if(modal)return;const token=++transition;if(id==='shopPip')closeItem();const stage=$(id).parentElement,graph=id==='hubPip'?'village':'shop';const points=PipNavigation.route(graph,positions[id],destination,stage.getBoundingClientRect());const arrive=()=>{if(token!==transition)return;$(id).classList.remove('face-left');$(id).dataset.navigation='standing';action();};walk={id,points,action:arrive};$(id).dataset.navigation='walking';if(matchMedia('(prefers-reduced-motion: reduce)').matches){positions[id]={...points.at(-1)};place(id);walk=null;arrive();}}
  function enter(id,action){const token=++transition;$(id).dataset.navigation='entering';$(id).classList.add('entering');setTimeout(()=>{if(token!==transition)return;$(id).classList.remove('entering');$(id).dataset.navigation='standing';action();},matchMedia('(prefers-reduced-motion: reduce)').matches?0:140);}
  function frame(time){const dt=Math.min((time-last)/1000,.04);last=time;if(walk&&!modal){const w=walk,p=positions[w.id],target=w.points[0],dx=target.x-p.x,dy=target.y-p.y,d=Math.hypot(dx,dy),node=$(w.id);node.classList.add('walking');node.style.setProperty('--walk-frame',Math.floor(time/90)%8);if(Math.abs(dx)>.1)node.classList.toggle('face-left',dx<0);if(d<dt*23){p.x=target.x;p.y=target.y;w.points.shift();if(!w.points.length){walk=null;node.classList.remove('walking');w.action();}}else{p.x+=dx/d*dt*23;p.y+=dy/d*dt*23;}place(w.id);}requestAnimationFrame(frame);}
  function openShop(){if(api.state.running&&!api.supplies.atStop)return;api.stopVoice();setScene('shop');closeItem();renderShop();}
  function renderShop(){const stock=api.stock(),shelf=$('shopShelf');$('shopBalance').textContent=(api.state.running?api.supplies.stars+' run':api.state.coins+' saved');$('shopExit').textContent=api.state.running?'Continue trail':'Leave shop';shelf.replaceChildren();stock.forEach((item,i)=>{const x=27+i*46/Math.max(1,stock.length-1),b=el('button',{class:'shelf-item','data-inspect':item.id,style:`left:${x}%`});b.append(el('img',{src:`assets/journey/items/${item.art||item.id}.webp`,alt:''}),el('span',{},item.name));b.onclick=()=>walkTo('shopPip',['left','middle','right'][Math.min(2,i)],()=>inspect(item.id));shelf.append(b);});}
  function inspect(id){const item=api.stock().find(i=>i.id===id);if(!item)return;$('itemArt').src=`assets/journey/items/${item.art||id}.webp`;$('itemName').textContent=item.name;$('itemDetail').textContent=item.detail;$('itemFacts').textContent=item.cosmetic?`${item.stars} saved stars · ${item.owned?'Owned':'Not owned'} · ${'◆'.repeat(Math.min(item.checkpoints,api.state.checkpoints))}${'◇'.repeat(Math.max(0,item.checkpoints-api.state.checkpoints))} ${Math.min(api.state.checkpoints,item.checkpoints)}/${item.checkpoints} beacons restored. Light ${item.checkpoints} beacons to unlock.`:`${item.cost} run stars · ${item.label} · Lasts for this run only.`;$('itemPreview').hidden=id!=='chime';$('itemPreview').onclick=()=>{api.previewSound();$('itemPreview').textContent=api.state.audioOn?'Preview sound':'Sound is muted';};const b=$('itemBuy');b.textContent=item.label;b.disabled=item.disabled;b.onclick=()=>{api.purchase(id);renderShop();inspect(id);};$('itemCard').hidden=false;$('supplyScene').classList.add('inspecting');$('itemClose').focus({preventScroll:true});}
  function renderWardrobe(){const wardrobe=api.wardrobe,items=$('wardrobeItems');items.replaceChildren();for(const item of wardrobe.items){const b=el('button',{'aria-pressed':String(item.id===wardrobe.selected)},item.name+' · '+(item.owned?'Owned':item.cost+' saved stars'));b.onclick=()=>{wardrobe.select(item.id);renderWardrobe();};items.append(b);}const selected=wardrobe.items.find(i=>i.id===wardrobe.selected);$('wardrobePreview').style.backgroundImage='url("'+selected.art+'")';$('wardrobeBalance').textContent=wardrobe.balance+' saved stars';$('wardrobeBuy').textContent=selected.owned?'Wear this outfit':'Keep outfit · '+selected.cost+' saved stars';$('wardrobeBuy').disabled=!selected.owned&&wardrobe.balance<selected.cost;$('wardrobeBuy').onclick=()=>{wardrobe.buyOrEquip();renderWardrobe();$('shopBalance').textContent=wardrobe.balance+' saved';};}
  function attach(gameApi){
    api=gameApi;
    const hub=el('section',{id:'villageHub',class:'world-scene','aria-label':"Pip’s English village"});hub.innerHTML=`<div class="scene-stage village-stage" id="villageStage"><header class="scene-heading"><small>Welcome to</small><h1>Pip’s English</h1><p>Choose a place. Pip will lead the way.</p></header><div class="scene-wallet">✦ <span id="hubStars"></span></div><button class="world-sign" id="hubBook" style="left:25%;top:34%">Word book</button><button class="world-sign" id="hubMap" style="left:43%;top:29%">Map</button><button class="world-sign" id="hubShop" style="left:64%;top:29%">Supply stop</button><button class="world-sign gold-sign" id="hubPlay" style="left:91.5%;top:42%">Go play</button><button class="resting-spot" data-destination="book" style="left:27%;top:57%" aria-label="Walk to the Word book"></button><button class="resting-spot" data-destination="map" style="left:43%;top:53%" aria-label="Walk to the map"></button><button class="resting-spot" data-destination="shop" style="left:63%;top:57%" aria-label="Walk to the Supply stop"></button><button class="resting-spot" data-destination="play" style="left:80%;top:75.5%" aria-label="Walk to Go play"></button><div id="hubPip" class="scene-pip" aria-hidden="true"><div class="pip-atlas-frame"></div></div><button id="hubSound" class="world-sign sound-sign">Sound</button></div>`;$('game').append(hub);
    const shop=el('section',{id:'supplyScene',class:'world-scene',hidden:'','aria-label':'Supply stop'});shop.innerHTML=`<div class="scene-stage shop-stage"><header class="scene-heading"><small>Pip’s</small><h1>Supply stop</h1><p>Choose a treasure to take a closer look.</p><button id="shopWardrobe" class="wood-button">Wardrobe</button></header><div class="scene-wallet">✦ <span id="shopBalance"></span></div><div id="shopShelf"></div><div id="shopPip" class="scene-pip" aria-hidden="true"><div class="pip-atlas-frame"></div></div><button id="shopExit" class="world-sign">Leave shop</button><section id="itemCard" class="item-card" hidden aria-label="Item details"><button id="itemClose" class="close-mark" aria-label="Close item">×</button><img id="itemArt" alt=""><h2 id="itemName"></h2><p id="itemDetail"></p><p id="itemFacts"></p><button id="itemPreview" class="wood-button" hidden>Preview sound</button><button id="itemBuy" class="wood-button"></button></section></div>`;$('game').append(shop);
    panel('wardrobePanel','Pip’s wardrobe','<div class="parchment wardrobe-panel"><button id="wardrobeClose" class="close-mark" aria-label="Close wardrobe">×</button><h1>Pip’s wardrobe</h1><p>Try anything for free. Keep an outfit with saved stars.</p><div id="wardrobePreview" class="pip-atlas-frame"></div><p id="wardrobeBalance"></p><div id="wardrobeItems"></div><button id="wardrobeBuy" class="wood-button"></button></div>');
    $('shopWardrobe').onclick=()=>{api.wardrobe.open();renderWardrobe();open($('wardrobePanel'));};$('wardrobeClose').onclick=()=>close($('wardrobePanel'));
    panel('playSetup','Start a journey',`<div class="parchment"><button id="playClose" class="close-mark" aria-label="Close play setup">×</button><p class="eyebrow">The rescue begins</p><h1>Let’s go, Pip!</h1><div class="mode-switch"><button data-play-mode="learning">Learning<span>Calm, guided practice</span></button><button data-play-mode="classic">Classic<span>Adventure & surprises</span></button></div><p id="playModeHelp"></p><label class="adverb-option"><input id="playAdverbs" type="checkbox"> Include adverbs in practice</label><button id="startJourney" class="wood-button">Start the journey</button></div>`);
    panel('journeyMap','Journey map',`<div class="map-shell"><header><div><p class="eyebrow">Pip’s rescue trail</p><h1>The floating islands</h1><p>Tap a beacon to see your records.</p></div><button id="mapClose" class="wood-button">Close map</button></header><div class="map-layout"><div class="map-frame"><div id="mapBoard" class="map-board"></div></div><div id="mapDetail" class="map-detail"></div></div></div>`);
    panel('routeChoice','Choose the next path',`<div class="parchment route-parchment"><p class="eyebrow">Beacon restored!</p><h1>Which way, Pip?</h1><h2 id="nextRegion"></h2><div id="routeCards"></div></div>`);
    panel('checkpointStop','A rest at the beacon',`<div class="parchment"><p class="eyebrow">Beacon restored!</p><h1>A little rest?</h1><p>You have <strong id="stopStars"></strong> run stars. Trade them for a rescue, a missing heart or a word-type reveal. These supplies last for this run only.</p><div class="dialog-actions"><button id="visitStop" class="wood-button">Visit supply stop</button><button id="skipStop" class="wood-button">Continue journey</button></div></div>`);
    panel('leaveConfirm','Return to the village',`<div class="parchment"><h1>Return to the village?</h1><p>Your cosmetic stars and best scores are saved. Unspent run stars and run aids end with this journey.</p><div class="dialog-actions"><button id="keepPlaying" class="wood-button">Keep playing</button><button id="leaveRun" class="wood-button">Return to village</button></div></div>`);
    const nav=el('nav',{class:'adventure-nav','aria-label':'Journey navigation'});nav.innerHTML='<button id="runMap">Map</button><button id="runHome">Village</button><span id="routeBadge"></span>';$('game').append(nav);
    const destinations={book:()=>enter('hubPip',()=>{hideHub();api.openBook();}),map:showMap,shop:()=>enter('hubPip',openShop),play:showPlay};const visit=destination=>walkTo('hubPip',destination,destinations[destination]);$('hubBook').onclick=()=>visit('book');$('hubMap').onclick=()=>visit('map');$('hubShop').onclick=()=>visit('shop');$('hubPlay').onclick=()=>visit('play');document.querySelectorAll('.resting-spot').forEach(spot=>spot.onclick=()=>visit(spot.dataset.destination));$('hubSound').onclick=()=>api.toggleSound();
    shop.append($('itemCard'));
    $('shopExit').onclick=()=>{closeItem();walkTo('shopPip','exit',()=>enter('shopPip',()=>{if(resolveStop){api.supplies.leave();hideHub();const done=resolveStop;resolveStop=null;done();}else showHub('shop');}));};$('itemClose').onclick=()=>{closeItem();$('shopShelf').querySelector('button')?.focus();};
    $('playClose').onclick=()=>close($('playSetup'));$('mapClose').onclick=()=>close($('journeyMap'));document.querySelectorAll('[data-play-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.playMode));$('startJourney').onclick=()=>{api.state.includeAdverbs=$('playAdverbs').checked;resetRun();close($('playSetup'));hideHub();api.beginStory();};
    $('runMap').onclick=()=>{if(!api.state.busy)showMap();};$('runHome').onclick=()=>{if(api.state.busy)return;if(api.state.running)open($('leaveConfirm'));else showHub();};$('keepPlaying').onclick=()=>close($('leaveConfirm'));$('leaveRun').onclick=()=>{record(api.state.phase,api.state.score-api.state.stageStart);close($('leaveConfirm'));showHub();};
    document.addEventListener('keydown',e=>{if(!modal)return;if(e.key==='Escape'&&!resolveRoute&&!resolveStop){close(modal);return;}if(e.key==='Tab'){const buttons=[...modal.querySelectorAll('button:not(:disabled),input')].filter(b=>!b.hidden);if(e.shiftKey&&document.activeElement===buttons[0]){e.preventDefault();buttons.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===buttons.at(-1)){e.preventDefault();buttons[0]?.focus();}}});
    place('hubPip');place('shopPip');api.wardrobe.refresh();setMode(mode);requestAnimationFrame(frame);
  }
  window.PipAdventure={attach,settings,apply,record,chooseNext,checkpointStop,showHub,hideHub,openShop,resetRun,get mode(){return mode;},get regions(){return regions;}};
})();
