/* Scene navigation and saved journey records; game rules stay in game.js. */
(() => {
  'use strict';
  const $=id=>document.getElementById(id);
  const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem('pip_english_'+key))??fallback;}catch{return fallback;}};
  const save=(key,value)=>{try{localStorage.setItem('pip_english_'+key,JSON.stringify(value));}catch{}};
  const regions={
    2:{name:'Sky Islands',story:'Light the sky beacon and help the villagers find a safe path.',routes:[['sky','Sunbeam Village','A gentle beginning'],['sky-alt','Cloud Harbour','Double stars · extra adverbs']]},
    3:{name:'Floating Forest',story:'The forest homes are drifting apart. Follow the fireflies to their beacon.',routes:[['forest','Waterfall Woods','Double stars · extra adverbs'],['forest-alt','Moonlit Canopy','Phase 2 words · half stars']]},
    4:{name:'Crystal Peaks',story:'Guide the mountain villagers across the frozen sky.',routes:[['crystal','Crystal Caverns','Double stars · extra adverbs'],['crystal-alt','Aurora Glacier','Phase 3 words · half stars']]},
    5:{name:'Ember Volcano',story:'Bring the last beacon’s light home and settle the floating islands.',routes:[['volcano','Ember Ascent','Double stars · extra adverbs'],['volcano-alt','Lava Lanterns','Phase 4 words · half stars']]}
  };
  let mode='learning',route=0,api,scene='village',mapPhase=2,resolveRoute,focusBefore,modal;
  const records=read('records',{}),positions={hubPip:{x:50,y:80},shopPip:{x:50,y:85}};
  let walk=null,last=0;
  const settings=phase=>({mode,route,wordPhase:mode==='classic'&&route===1&&phase>2?phase-1:phase,extraAdverbs:mode==='classic'&&((route===0&&phase>2)||(route===1&&phase===2)),multiplier:mode==='learning'?1:route===1&&phase>2?.5:((route===0&&phase>2)||(route===1&&phase===2))?2:1});
  function unlock(){let legacy=2;if(mode==='classic'){try{legacy=JSON.parse(localStorage.getItem('wordwind_unlockedPhase')||'2');}catch{}}return Math.max(2,Math.min(5,Number(read('unlocked_'+mode,legacy))||2));}
  const recordKey=(p,r=route)=>`${mode}:${p}:${r}`;
  function record(phase,score,complete=false){const key=recordKey(phase),old=records[key];records[key]={best:Math.max(old?.best||0,score),complete:!!(complete||old?.complete)};save('records',records);if(complete)save('unlocked_'+mode,Math.max(unlock(),Math.min(5,phase+1)));}
  function el(tag,attrs={},text=''){const e=document.createElement(tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));e.textContent=text;return e;}
  function panel(id,title,html){const p=el('section',{id,class:'scene-dialog',role:'dialog','aria-modal':'true','aria-label':title,hidden:''});p.innerHTML=html;$('game').append(p);return p;}
  function inert(){[...$('game').children].forEach(e=>{e.inert=modal?e!==modal:scene==='village'?e!==$('villageHub'):scene==='shop'?e!==$('supplyScene'):false;});}
  function sceneMusic(){PipSoundtrack.scene(modal===$('journeyMap')?'map':scene==='game'?({2:'sky',3:'forest',4:'crystal',5:'volcano'}[api.state.phase]):scene);}
  function open(p){focusBefore=document.activeElement;modal=p;p.hidden=false;api.stopVoice();inert();p.querySelector('button')?.focus();sceneMusic();}
  function close(p){p.hidden=true;modal=null;inert();focusBefore?.focus({preventScroll:true});api.ground();sceneMusic();}
  function setScene(next){scene=next;walk=null;$('hubPip').classList.remove('walking');$('shopPip').classList.remove('walking');$('villageHub').hidden=next!=='village';$('supplyScene').hidden=next!=='shop';$('game').classList.toggle('in-village',next!=='game');inert();sceneMusic();}
  function showHub(){api.state.running=false;api.state.busy=false;api.stopVoice();api.hideMenus();document.querySelectorAll('.scene-dialog').forEach(e=>e.hidden=true);modal=null;setScene('village');setMode(mode);$('hubStars').textContent=api.state.coins;}
  function hideHub(){setScene('game');}
  function setMode(value){mode=value;api.state.unlockedPhase=unlock();api.state.selectedPhase=2;$('game').dataset.mode=mode;document.querySelectorAll('[data-play-mode]').forEach(e=>e.setAttribute('aria-pressed',String(e.dataset.playMode===mode)));$('playModeHelp').textContent=mode==='learning'?'Free explanations and gentle retries. No powerups or surprise rules.':'Choose branching routes with star bonuses and surprises. Three word-type reveals per run.';api.refresh();}
  function apply(phase){const r=regions[phase].routes[route];$('skyScene').style.backgroundImage=`url("assets/journey/${r[0]}.webp")`;$('routeBadge').textContent=r[1];sceneMusic();}
  function showPlay(){setMode('learning');$('playAdverbs').checked=api.state.includeAdverbs;open($('playSetup'));}
  function resetRun(){route=0;api.state.selectedPhase=2;}
  function showMap(){mapPhase=api.state.running?api.state.phase:2;renderMap();open($('journeyMap'));}
  function renderMap(){
    const board=$('mapBoard'),detail=$('mapDetail');board.replaceChildren(el('img',{src:'assets/journey/map.webp',alt:'The floating-island trail.'}));
    [5,4,3,2].forEach(phase=>{const locked=phase>unlock(),top={2:84,3:58,4:36,5:18}[phase];if(locked)board.append(el('div',{class:'map-fog',style:`top:${top-14}%;height:26%`,'aria-hidden':'true'}));const b=el('button',{class:'map-stop'+(phase===mapPhase?' selected':''),'data-phase':phase,style:`top:${top}%;left:50%`},locked?'🔒 ????':regions[phase].name);b.onclick=()=>{mapPhase=phase;renderMap();};board.append(b);});
    detail.replaceChildren();if(mapPhase>unlock()){detail.append(el('h2',{},'🔒 ????'),el('p',{},'Restore the previous beacon to discover this place.'));return;}
    detail.append(el('p',{class:'eyebrow'},mode==='learning'?'Learning journey':'Classic journey'),el('h2',{},regions[mapPhase].name),el('p',{},regions[mapPhase].story));
    regions[mapPhase].routes.forEach(([asset,name],r)=>{const rec=records[recordKey(mapPhase,r)],card=el('article',{class:'route-card'});card.append(el('img',{src:`assets/journey/${asset}.webp`,alt:'',loading:'lazy'}),el('h3',{},name),el('p',{},rec?`Best: ${rec.best} correct leaps${rec.complete?' · Beacon lit':''}`:'Not travelled yet'));detail.append(card);});detail.append(el('p',{},'Start at Go play in the village. Choose your next path as you travel.'));
  }
  function chooseNext(phase){record(phase,api.state.score-api.state.stageStart,true);$('nextRegion').textContent=regions[phase+1].name;const cards=$('routeCards');cards.replaceChildren();return new Promise(resolve=>{resolveRoute=resolve;regions[phase+1].routes.forEach(([asset,name,rule],i)=>{const b=el('button',{class:'route-card'});b.append(el('img',{src:`assets/journey/${asset}.webp`,alt:''}),el('h3',{},name),el('p',{},mode==='learning'?'A new path · the same gentle learning':rule));b.onclick=()=>{route=i;close($('routeChoice'));resolveRoute=null;resolve(i);};cards.append(b);});open($('routeChoice'));});}
  function place(id){const p=positions[id];$(id).style.left=p.x+'%';$(id).style.top=p.y+'%';}
  function walkTo(id,x,y,action){if(modal)return;const p=positions[id],lane=id==='hubPip'?86:88;walk={id,points:[{x:p.x,y:lane},{x,y:lane},{x,y}],action};}
  function frame(time){const dt=Math.min((time-last)/1000,.04);last=time;if(walk&&!modal){const w=walk,p=positions[w.id],target=w.points[0],dx=target.x-p.x,dy=target.y-p.y,d=Math.hypot(dx,dy),node=$(w.id);node.classList.add('walking');node.style.setProperty('--walk-frame',Math.floor(time/90)%8);if(Math.abs(dx)>.1)node.classList.toggle('face-left',dx<0);if(d<dt*23){p.x=target.x;p.y=target.y;w.points.shift();if(!w.points.length){walk=null;node.classList.remove('walking');w.action();}}else{p.x+=dx/d*dt*23;p.y+=dy/d*dt*23;}place(w.id);}requestAnimationFrame(frame);}
  function openShop(){if(api.state.running&&api.state.busy)return;api.stopVoice();setScene('shop');$('itemCard').hidden=true;renderShop();}
  function renderShop(){const stock=api.stock().filter(i=>mode==='classic'||i.cosmetic),shelf=$('shopShelf');$('shopBalance').textContent=api.state.coins;shelf.replaceChildren();stock.forEach((item,i)=>{const x=17+i*66/Math.max(1,stock.length-1),b=el('button',{class:'shelf-item','data-inspect':item.id,style:`left:${x}%`});b.append(el('img',{src:`assets/journey/items/${item.id}.webp`,alt:''}),el('span',{},item.name));b.onclick=()=>walkTo('shopPip',x,85,()=>inspect(item.id));shelf.append(b);});}
  function inspect(id){const item=api.stock().find(i=>i.id===id);if(!item)return;$('itemArt').src=`assets/journey/items/${id}.webp`;$('itemName').textContent=item.name;$('itemDetail').textContent=item.detail;const b=$('itemBuy');b.textContent=item.label;b.disabled=item.disabled;b.onclick=()=>{api.purchase(id);renderShop();inspect(id);};$('itemCard').hidden=false;$('itemClose').focus();}
  function attach(gameApi){
    api=gameApi;
    const hub=el('section',{id:'villageHub',class:'world-scene','aria-label':"Pip’s English village"});hub.innerHTML=`<div class="scene-stage village-stage" id="villageStage"><header class="scene-heading"><small>Welcome to</small><h1>Pip’s English</h1><p>Choose a place. Pip will lead the way.</p></header><div class="scene-wallet">✦ <span id="hubStars"></span></div><button class="world-sign" id="hubBook" style="left:25%;top:59%">Word book</button><button class="world-sign" id="hubMap" style="left:43%;top:43%">Map</button><button class="world-sign" id="hubShop" style="left:66%;top:55%">Supply stop</button><button class="world-sign gold-sign" id="hubPlay" style="left:89%;top:74%">Go play</button><div id="hubPip" class="scene-pip" aria-hidden="true"><div class="pip-atlas-frame"></div></div><button id="hubSound" class="world-sign sound-sign">Sound</button></div>`;$('game').append(hub);
    const shop=el('section',{id:'supplyScene',class:'world-scene',hidden:'','aria-label':'Supply stop'});shop.innerHTML=`<div class="scene-stage shop-stage"><header class="scene-heading"><small>Pip’s</small><h1>Supply stop</h1><p>Choose a treasure to take a closer look.</p></header><div class="scene-wallet">✦ <span id="shopBalance"></span></div><div id="shopShelf"></div><div id="shopPip" class="scene-pip" aria-hidden="true"><div class="pip-atlas-frame"></div></div><button id="shopExit" class="world-sign">Leave shop</button><section id="itemCard" class="item-card" hidden aria-label="Item details"><button id="itemClose" class="close-mark" aria-label="Close item">×</button><img id="itemArt" alt=""><h2 id="itemName"></h2><p id="itemDetail"></p><button id="itemBuy" class="wood-button"></button></section></div>`;$('game').append(shop);
    panel('playSetup','Start a journey',`<div class="parchment"><button id="playClose" class="close-mark" aria-label="Close play setup">×</button><p class="eyebrow">The rescue begins</p><h1>Let’s go, Pip!</h1><div class="mode-switch"><button data-play-mode="learning">Learning<span>Calm, guided practice</span></button><button data-play-mode="classic">Classic<span>Adventure & surprises</span></button></div><p id="playModeHelp"></p><label class="adverb-option"><input id="playAdverbs" type="checkbox"> Include adverbs in practice</label><button id="startJourney" class="wood-button">Start the journey</button></div>`);
    panel('journeyMap','Journey map',`<div class="map-shell"><header><div><p class="eyebrow">Pip’s rescue trail</p><h1>The floating islands</h1><p>Tap a beacon to see your records.</p></div><button id="mapClose" class="wood-button">Close map</button></header><div class="map-layout"><div id="mapBoard" class="map-board"></div><div id="mapDetail" class="map-detail"></div></div></div>`);
    panel('routeChoice','Choose the next path',`<div class="parchment route-parchment"><p class="eyebrow">Beacon restored!</p><h1>Which way, Pip?</h1><h2 id="nextRegion"></h2><div id="routeCards"></div></div>`);
    panel('leaveConfirm','Return to the village',`<div class="parchment"><h1>Return to the village?</h1><p>Your stars and best scores are saved. This run will end.</p><div class="dialog-actions"><button id="keepPlaying" class="wood-button">Keep playing</button><button id="leaveRun" class="wood-button">Return to village</button></div></div>`);
    const nav=el('nav',{class:'adventure-nav','aria-label':'Journey navigation'});nav.innerHTML='<button id="runMap">Map</button><button id="runHome">Village</button><span id="routeBadge"></span>';$('game').append(nav);
    $('hubBook').onclick=()=>walkTo('hubPip',25,86,()=>{hideHub();api.openBook();});$('hubMap').onclick=()=>walkTo('hubPip',43,73,showMap);$('hubShop').onclick=()=>walkTo('hubPip',66,84,openShop);$('hubPlay').onclick=()=>walkTo('hubPip',89,96,showPlay);$('hubSound').onclick=()=>api.toggleSound();
    $('shopExit').onclick=()=>{if(!$('itemCard').hidden)$('itemCard').hidden=true;walkTo('shopPip',50,94,()=>api.state.running?hideHub():showHub());};$('itemClose').onclick=()=>{$('itemCard').hidden=true;$('shopShelf').querySelector('button')?.focus();};
    $('playClose').onclick=()=>close($('playSetup'));$('mapClose').onclick=()=>close($('journeyMap'));document.querySelectorAll('[data-play-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.playMode));$('startJourney').onclick=()=>{api.state.includeAdverbs=$('playAdverbs').checked;resetRun();close($('playSetup'));hideHub();api.beginStory();};
    $('runMap').onclick=()=>{if(!api.state.busy)showMap();};$('runHome').onclick=()=>{if(api.state.busy)return;if(api.state.running)open($('leaveConfirm'));else showHub();};$('keepPlaying').onclick=()=>close($('leaveConfirm'));$('leaveRun').onclick=()=>{record(api.state.phase,api.state.score-api.state.stageStart);close($('leaveConfirm'));showHub();};
    document.addEventListener('keydown',e=>{if(!modal)return;if(e.key==='Escape'&&!resolveRoute){close(modal);return;}if(e.key==='Tab'){const buttons=[...modal.querySelectorAll('button:not(:disabled),input')].filter(b=>!b.hidden);if(e.shiftKey&&document.activeElement===buttons[0]){e.preventDefault();buttons.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===buttons.at(-1)){e.preventDefault();buttons[0]?.focus();}}});
    place('hubPip');place('shopPip');setMode(mode);requestAnimationFrame(frame);
  }
  window.PipAdventure={attach,settings,apply,record,chooseNext,showHub,hideHub,openShop,resetRun,get mode(){return mode;},get regions(){return regions;}};
})();
