const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert/strict');
const root=path.join(__dirname,'..');
const server=http.createServer((req,res)=>{try{const file=path.join(root,req.url.split('?')[0]==='/'?'index.html':req.url.split('?')[0]);let data=fs.readFileSync(file);if(file.endsWith('game.js'))data=Buffer.from(data.toString().replace('  buildTrail(); updatePhasePicker();','  window.testGame={state,startGame,showWordHelper,closeWordHelper,handleChoice,beginCheckpoint,buy};\n  buildTrail(); updatePhasePicker();'));res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.webp')?'image/webp':file.endsWith('.jpg')?'image/jpeg':'text/html');res.end(data);}catch{res.writeHead(404).end();}});
async function finishReview(page){await page.locator('#checkpointReview.open').waitFor();while((await page.locator('#checkpointReview').getAttribute('class')).includes('open'))await page.click('#reviewNext');}
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'chrome',headless:true});try{const page=await browser.newPage({viewport:{width:1024,height:768}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>localStorage.setItem('wordwind_audioOn','false'));await page.route('**/api/dictionary?*',r=>{const word=new URL(r.request().url()).searchParams.get('word');return r.fulfill({json:[{meta:{id:word},fl:'noun',shortdef:['A child-friendly meaning for '+word]}]});});await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>window.testGame&&!document.getElementById('loadingOverlay').classList.contains('open'));await page.screenshot({path:path.join(__dirname,'adventure-hub.png')});
await page.click('#hubMap');await page.locator('#journeyMap:not([hidden])').waitFor();assert.equal(await page.locator('.map-frame').count(),1);assert.equal(await page.locator('.familiar-drawer').count(),1);assert.equal(await page.locator('.familiar-drawer').getAttribute('open'),null);await page.click('.map-stop[data-phase="5"]');assert.match(await page.locator('#mapDetail').innerText(),/\?\?\?\?/);assert.equal(await page.locator('#mapDetail button').count(),0);await page.screenshot({path:path.join(__dirname,'adventure-map.png')});await page.click('#mapClose');await page.click('#hubPlay');await page.locator('#playSetup:not([hidden])').waitFor();assert.equal(await page.evaluate(()=>PipAdventure.mode),'learning');await page.click('[data-play-mode="classic"]');await page.click('#playClose');await page.click('#hubShop');await page.locator('#supplyScene:not([hidden])').waitFor();await page.evaluate(()=>{testGame.state.coins=100;});await page.click('[data-inspect="aqua"]');await page.screenshot({path:path.join(__dirname,'adventure-shop.png')});await page.evaluate(()=>testGame.buy('heart'));const balance=await page.evaluate(()=>testGame.state.coins);await page.evaluate(()=>testGame.buy('heart'));assert.equal(await page.evaluate(()=>testGame.state.coins),balance);await page.click('#shopExit');await page.locator('#villageHub:not([hidden])').waitFor();
await page.click('#hubPlay');await page.locator('#playSetup:not([hidden])').waitFor();await page.click('[data-play-mode="classic"]');await page.click('#startJourney');await page.locator('#storyOverlay.open').waitFor();await page.click('#storySkipButton');await page.waitForFunction(()=>testGame.state.running&&!testGame.state.busy);
for(const word of ['cat','dog']){await page.evaluate(w=>testGame.showWordHelper(w,'noun',2),word);assert.equal(await page.locator('#helperKind').textContent(),'Picture clue');await page.click('#helperReveal');assert.equal(await page.locator('#helperKind').textContent(),'noun picture');await page.click('#wordHelperClose');}
await page.evaluate(()=>testGame.showWordHelper('hen','noun',2));assert(await page.locator('#helperReveal').isDisabled());assert(await page.locator('#helperNext').isHidden());await page.click('#wordHelperClose');assert.equal(await page.evaluate(()=>testGame.state.clues),0);
for(let i=0;i<6;i++){await page.waitForFunction(()=>!testGame.state.busy);await page.evaluate(async()=>{const s=testGame.state;const e=[...document.querySelectorAll('#choices>.island')].find(e=>PipVocabulary.accepts(e.dataset.word,s.targetKind));await testGame.handleChoice(e);});}await page.waitForFunction(()=>testGame.state.bossMode&&!testGame.state.busy);while(await page.evaluate(()=>testGame.state.bossRemaining>0)){const last=await page.evaluate(()=>testGame.state.bossRemaining===1);await page.locator('#choices>[data-boss-correct="true"]:not(.boss-cleared)').first().dispatchEvent('click');if(last){await finishReview(page);await page.locator('#checkpointStop:not([hidden])').waitFor();await page.click('#visitStop');await page.locator('#supplyScene:not([hidden])').waitFor();const saved=await page.evaluate(()=>testGame.state.coins);const wallet=await page.evaluate(()=>PipSupplies.stars);await page.click('[data-inspect="reveal"]');await page.locator('#itemCard:not([hidden])').waitFor();await page.click('#itemBuy');assert.equal(await page.evaluate(()=>testGame.state.clues),1);assert.equal(await page.evaluate(()=>PipSupplies.stars),wallet-2);assert.equal(await page.evaluate(()=>testGame.state.coins),saved);assert(await page.locator('#itemBuy').isDisabled());await page.screenshot({path:path.join(__dirname,'adventure-stop.png')});await page.click('#itemClose');await page.click('#shopExit');await page.locator('#routeChoice:not([hidden])').waitFor();break;}await page.waitForFunction(()=>!testGame.state.busy);assert(await page.evaluate(()=>testGame.state.anchor.classList.contains('boss-cleared')));}
assert.equal(await page.locator('#routeCards .route-node').count(),2);assert.equal(await page.locator('#routeConfirm').count(),0);await page.locator('#routeCards .route-node').nth(1).click();assert.match(await page.locator('#routeDetail').innerText(),/Moonlit Canopy/);assert.equal(await page.locator('#routeForkMap').getAttribute('data-selected'),'1');await page.screenshot({path:path.join(__dirname,'adventure-route.png')});await page.setViewportSize({width:390,height:844});const routeBoxes=await page.locator('.route-node').evaluateAll(nodes=>nodes.map(node=>{const r=node.getBoundingClientRect();return {width:r.width,height:r.height,left:r.left,right:r.right};}));for(const box of routeBoxes){assert(box.width>=44&&box.height>=44);assert(box.left>=0&&box.right<=390);}await page.locator('#routeConfirm').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(__dirname,'adventure-route-phone.png')});await page.setViewportSize({width:1024,height:768});await page.click('#routeConfirm');await page.waitForFunction(()=>testGame.state.phase===3&&!testGame.state.busy);assert.equal(await page.evaluate(()=>PipAdventure.settings(3).wordPhase),2);assert.equal(await page.evaluate(()=>PipAdventure.settings(3).multiplier),.5);await page.waitForTimeout(600);await page.screenshot({path:path.join(__dirname,'adventure-game.png')});
await page.evaluate(()=>PipAdventure.showHub());await page.click('#hubPlay');await page.locator('#playSetup:not([hidden])').waitFor();await page.click('[data-play-mode="learning"]');await page.click('#playClose');assert.equal(await page.evaluate(()=>testGame.state.unlockedPhase),2);await page.evaluate(()=>testGame.startGame());await page.evaluate(()=>testGame.showWordHelper('cat','noun',2));assert.equal(await page.locator('#helperKind').textContent(),'noun picture');assert(await page.locator('#helperReveal').isHidden());await page.click('#wordHelperClose');const hearts=await page.evaluate(()=>testGame.state.hearts);await page.evaluate(async()=>{let e;for(let i=0;i<20;i++){const s=testGame.state;e=[...document.querySelectorAll('#choices>.island')].find(e=>!PipVocabulary.accepts(e.dataset.word,s.targetKind));if(e)break;testGame.startGame();}if(!e)throw Error('No wrong option generated');await testGame.handleChoice(e);});assert.equal(await page.evaluate(()=>testGame.state.hearts),hearts);

// Finish all Learning beacons through the actual multi-island transition path.
for(let phase=2;phase<=5;phase++){
  await page.evaluate(()=>testGame.beginCheckpoint());await page.waitForFunction(()=>!testGame.state.busy);
  while(await page.evaluate(()=>testGame.state.bossRemaining>0)){
    const last=await page.evaluate(()=>testGame.state.bossRemaining===1);
    await page.locator('#choices>[data-boss-correct="true"]:not(.boss-cleared)').first().dispatchEvent('click');
    if(last){await finishReview(page);if(phase<5){await page.locator('#routeChoice:not([hidden])').waitFor();await page.locator('#routeCards .route-node').first().click();await page.click('#routeConfirm');await page.waitForFunction(p=>testGame.state.phase===p&&!testGame.state.busy,phase+1);}else{await page.locator('#resultOverlay.open').waitFor();assert(await page.evaluate(()=>document.getElementById('game').classList.contains('run-won')));}break;}
    await page.waitForFunction(()=>!testGame.state.busy);
  }
}
await page.screenshot({path:path.join(__dirname,'adventure-victory.png')});
await page.click('#againButton');await page.waitForFunction(()=>testGame.state.running&&!testGame.state.busy);assert(await page.evaluate(()=>!document.getElementById('pip').classList.contains('fall')));

await page.setViewportSize({width:390,height:844});await page.evaluate(()=>PipAdventure.showHub());await page.screenshot({path:path.join(__dirname,'adventure-phone.png')});const bad=await page.evaluate(async()=>{const missing=[];for(const e of PipVocabulary.entries){if(!(await fetch(e.image)).ok)missing.push(e.id);}return missing;});assert.deepEqual(bad,[]);assert.deepEqual(errors,[]);console.log('PASS: hub, shop inspect/purchase guard, map locks, branching checkpoint, mixed word bank, two reveals, Learning progress/retries, 496 URLs, no page errors.');}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
