const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert/strict'),root=path.join(__dirname,'..');
const server=http.createServer((req,res)=>{try{const file=path.join(root,req.url.split('?')[0]==='/'?'index.html':req.url.split('?')[0]);let data=fs.readFileSync(file);if(file.endsWith('game.js'))data=Buffer.from(data.toString().replace('  buildTrail(); updatePhasePicker();','  window.testGame={state,startGame,showResult,applyPhase,animatePipTo,groundPip,makeOptions,makeBossOptions,selection};\n  buildTrail(); updatePhasePicker();'));res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(data);}catch{res.writeHead(404).end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'chrome',headless:true});try{const page=await browser.newPage({viewport:{width:1024,height:768}});page.setDefaultTimeout(5000);await page.route('**/api/speech',r=>r.abort());await page.addInitScript(()=>{localStorage.setItem('wordwind_audioOn','false');const animate=Element.prototype.animate;Element.prototype.animate=function(frames,options){return animate.call(this,frames,typeof options==='object'?{...options,duration:1}:1);};});await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>window.testGame&&!document.getElementById('loadingOverlay').classList.contains('open'));
for(const success of [true,false]){await page.evaluate(success=>{testGame.startGame();testGame.state.running=false;testGame.showResult(success);},success);assert.equal(await page.locator('#choosePhaseButton').textContent(),'Back to village');const coins=await page.evaluate(()=>testGame.state.coins);await page.click('#choosePhaseButton');assert(await page.locator('#villageHub').isVisible());assert.equal(await page.evaluate(()=>testGame.state.coins),coins);}
await page.evaluate(()=>testGame.startGame());
for(const phase of [2,3,4,5])for(const direction of [-1,1,0]){const result=await page.evaluate(async({phase,direction})=>{testGame.applyPhase(phase);const pip=document.getElementById('pip'),world=document.getElementById('world'),island=document.createElement('div');island.className='island';island.style.cssText=`left:${direction<0?10:direction>0?80:50}%;top:55%;width:100px;height:80px`;world.append(island);if(direction===0)island.style.left=(pip.offsetLeft+pip.offsetWidth/2-island.offsetWidth/2)+'px';const prior=pip.classList.contains('face-left');await testGame.animatePipTo(island);const result={left:pip.classList.contains('face-left'),prior,scale:getComputedStyle(pip.querySelector('.pip-sprite')).scale};island.remove();testGame.groundPip(true);return result;},{phase,direction});assert.equal(result.left,direction===0?result.prior:direction<0);assert.equal(result.scale,direction<0||direction===0&&result.prior?'-1 1':'none');}
await page.evaluate(()=>testGame.startGame());assert.equal(await page.evaluate(()=>testGame.selection.history.length),1,'new run resets history then presents one round');for(const phase of [2,3,4,5]){const result=await page.evaluate(phase=>{testGame.state.phase=phase;testGame.state.targetKind='verb';return testGame.makeBossOptions(phase);},phase);assert.equal(result.filter(o=>o.bossCorrect).length,phase===5?3:2);}
console.log('PASS: both result returns preserve saved stars, all outfit jump directions/vertical facing, new-run history reset, integrated checkpoint counts.');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
