const vm=require('vm'),fs=require('fs'),assert=require('assert/strict');
let enabled=true,plays=[],contexts=[],callbacks={},delays=[],intervals=new Set();
class Node { constructor(){this.gain={value:0,setTargetAtTime(v){this.value=v;},cancelScheduledValues(){},setValueAtTime(){},linearRampToValueAtTime(){},exponentialRampToValueAtTime(){}};this.frequency={value:0};}connect(){return this;}disconnect(){this.disconnected=true;}start(){}stop(){} }
class Context {constructor(){contexts.push(this);this.currentTime=1;this.state='running';this.destination={};}createGain(){return new Node();}createOscillator(){return new Node();}createMediaElementSource(){return new Node();}resume(){return Promise.resolve();}}
class Audio{constructor(src){this.src=src;}play(){plays.push(this);this.paused=false;return Promise.resolve();}pause(){this.paused=true;}removeAttribute(){this.src='';}load(){}}
const document={hidden:false,addEventListener(k,f){callbacks[k]=f;}};
const scope={window:{AudioContext:Context},Audio,document,setTimeout:f=>delays.push(f),setInterval:f=>{intervals.add(f);return f;},clearInterval:f=>intervals.delete(f)};
vm.runInNewContext(fs.readFileSync(require('path').join(__dirname,'../soundtrack.js'),'utf8'),scope);
const music=scope.window.PipSoundtrack,flush=async()=>{await Promise.resolve();await Promise.resolve();};
(async()=>{music.configure({enabled:()=>enabled});music.scene('shop');assert.equal(plays.length,0,'must wait for gesture');music.unlock();await flush();assert.match(plays.at(-1).src,/shop-ambience/);const shop=plays.at(-1);music.scene('forest');assert.match(plays.at(-1).src,/forest-ambience/);delays.splice(0).forEach(f=>f());assert(shop.paused,'old scene stopped after fade');assert.equal(music.current,'forest');music.duck(true);music.duck(false);enabled=false;music.refresh();assert(plays.at(-1).paused);assert.equal(intervals.size,0);music.scene('volcano');enabled=true;music.refresh();await flush();assert.match(plays.at(-1).src,/volcano-ambience/);document.hidden=true;callbacks.visibilitychange();assert(plays.at(-1).paused);assert.equal(intervals.size,0);document.hidden=false;callbacks.visibilitychange();await flush();assert.equal(intervals.size,1);assert.equal(contexts.length,1);console.log('PASS: gesture gate, scene swap, fade cleanup, mute/resume, hidden-tab pause, one audio context; no paid calls.');})().catch(e=>{console.error(e);process.exitCode=1;});
