const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert/strict');
const root=path.join(__dirname,'..');
const server=http.createServer((req,res)=>{try{const file=path.join(root,req.url.split('?')[0]==='/'?'index.html':req.url.split('?')[0]);let data=fs.readFileSync(file);if(file.endsWith('game.js'))data=Buffer.from(data.toString().replace('  buildTrail(); updatePhasePicker();','  window.testGame={state,startGame};\n  buildTrail(); updatePhasePicker();'));res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.mp3')?'audio/mpeg':file.endsWith('.webp')?'image/webp':'text/html');res.end(data);}catch{res.writeHead(404).end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'chrome',headless:true});try{
  const page=await browser.newPage({viewport:{width:1024,height:768}}),errors=[],dialogs=[];
  page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>{dialogs.push(d.message());d.dismiss();});
  await page.route('**/api/speech',r=>r.abort()); // Never spend speech credits in tests.
  await page.addInitScript(()=>{localStorage.setItem('wordwind_audioOn','false');localStorage.setItem('wordwind_coins','100');localStorage.setItem('pip_english_unlocked_classic','5');localStorage.setItem('wordwind_selectedPhase','5');});
  await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>window.testGame&&!document.getElementById('loadingOverlay').classList.contains('open'));
  assert.equal(await page.locator('#villageHub [data-play-mode]').count(),0);
  const pos=await page.locator('#hubPip').getAttribute('style');await page.keyboard.press('ArrowRight');await page.locator('#villageStage').click({position:{x:500,y:450}});await page.waitForTimeout(250);assert.equal(await page.locator('#hubPip').getAttribute('style'),pos);
  await page.click('#hubSound');await page.waitForFunction(()=>PipSoundtrack.current==='village');
  await page.click('#hubMap');await page.locator('#journeyMap:not([hidden])').waitFor();assert.equal(await page.evaluate(()=>PipSoundtrack.current),'map');await page.click('.map-stop[data-phase="5"]');assert.match(await page.locator('#mapDetail').innerText(),/\?\?\?\?/);await page.click('#mapClose');assert.equal(await page.evaluate(()=>PipSoundtrack.current),'village');
  await page.screenshot({path:path.join(__dirname,'world-hub.png')});
  await page.click('#hubPlay');await page.locator('#playSetup:not([hidden])').waitFor();assert.equal(await page.evaluate(()=>PipAdventure.mode),'learning');await page.click('[data-play-mode="classic"]');await page.screenshot({path:path.join(__dirname,'world-play.png')});await page.click('#playClose');
  await page.click('#hubShop');await page.locator('#supplyScene:not([hidden])').waitFor();assert.equal(await page.evaluate(()=>PipSoundtrack.current),'shop');assert.equal(await page.locator('.shelf-item').count(),6);await page.click('[data-inspect="heart"]');await page.locator('#itemCard:not([hidden])').waitFor();await page.click('#itemBuy');assert.equal(await page.evaluate(()=>testGame.state.coins),70);assert(await page.locator('#itemBuy').isDisabled());await page.screenshot({path:path.join(__dirname,'world-shop.png')});await page.click('#itemClose');await page.click('#shopExit');await page.locator('#villageHub:not([hidden])').waitFor();
  await page.evaluate(()=>testGame.startGame());assert.equal(await page.evaluate(()=>testGame.state.phase),2);await page.click('#runHome');await page.locator('#leaveConfirm:not([hidden])').waitFor();await page.screenshot({path:path.join(__dirname,'world-confirm.png')});await page.click('#keepPlaying');assert(await page.evaluate(()=>testGame.state.running));await page.click('#runHome');await page.click('#leaveRun');await page.locator('#villageHub:not([hidden])').waitFor();assert.equal(await page.evaluate(()=>testGame.state.running),false);
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(__dirname,'world-phone.png')});await page.click('#hubPlay');await page.locator('#playSetup:not([hidden])').waitFor();assert.equal(await page.evaluate(()=>PipAdventure.mode),'learning');assert(await page.locator('#startJourney').isVisible());
  assert.deepEqual(dialogs,[]);assert.deepEqual(errors,[]);console.log('PASS: click-only movement, default Learning, map records/locks, scene music, shop purchase guard, Phase 2 start, in-game leave confirmation, mobile controls.');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
